### ISSUE TITLE
Request for support for private registries

### ISSUE THREAD

**Issue by casanova-21** [actions/setup-dotnet#419] opened 2023-05-11 18:38 UTC
Description:
My customer, Wells Fargo, is requesting that this Action be modified to provide support for publishing and downloading artifacts from a private repository. They're working on moving to GHEC, and have indicated that this is a critical blocker for them to be able to use this Action.

Justification:
Customer will not be allowing packages to be published or pulled to a public repository. It must all be internal.

Are you willing to submit a PR?
I'm willing but lack the developer chops to do this.

**Comment by IvanZosimov** [comment] 2023-05-12 09:13
Hi, @casanova-21 thanks for the feature request! We are going to take a look at it and get back to you with updates.

**Comment by casanova-21** [comment] 2023-05-12 14:57
Thank you very much @IvanZosimov!

**Comment by nikolai-laevskii** [comment] 2023-05-29 10:48
If your team moves on to GHEC, it might be safe to assume that you'll be using Github Packages. We have this case covered already: https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages

Could you please provide feedback whether it suits your current needs? And if not, elaborate further on your request. Thank you!

**Comment by casanova-21** [comment] 2023-05-30 14:29
Hi @nikolai-laevskii 👋 Thank you for the response. I can confirm that my customer won't be using Packages and will continue to use their private registry, Artifactory, after migrating to GHEC. So I will still need to request the functionality be added to this Action.

**Comment by kuhlman-labs** [comment] 2023-05-31 16:59
@nikolai-laevskii I see you support a `source-url` in the inputs, would this work if they passed in their Artifactory URL?

**Comment by casanova-21** [comment] 2023-06-28 19:10
@IvanZosimov Apologies for the delay in getting back to you on this. To answer your questions, no, to my knowledge our customer has not attempted to set up a custom NuGet feed. Looking at that documentation, it is intended to be used with GitHub Packages, Azure Artifacts, and nuget.org. I had mentioned above that my customer is adamant about using their internal Artifactory platform for the package registry. I just want to confirm that I'm not misunderstanding anything about the existing functionality of the Action that would give them a path forward to use Artifactory, or if adding new functionality to the Action is the only way to achieve what they want. Thank you!

**Comment by IvanZosimov** [comment] 2023-06-29 12:19
Hi, @casanova-21 👋 In my previous comment I just wanted to say that your customer can try to configure authentication to the their Artifactory using examples from this guide: https://github.com/actions/setup-dotnet/blob/main/README.md#setting-up-authentication-for-nuget-feeds and also it's possible to authenticate manually, using examples from these comments: https://github.com/actions/setup-dotnet/issues/415#issue-1688160580, https://github.com/actions/setup-dotnet/issues/167#issuecomment-1047221668

**Comment by IvanZosimov** [comment] 2023-09-01 07:37
Hi, @casanova-21 👋 I'm going to close this issue now as a duplicate of the https://github.com/actions/setup-dotnet/issues/415. Still, you can track the progress there.

**Closed** 2023-09-01 07:37 UTC
Labels: duplicate, feature request
