### ISSUE TITLE
GitHub Actions to push to Azure Artifacts: Unable to load the service index for source ' 'Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by benyusouf** [actions/setup-dotnet#370] opened 2023-01-13 15:14 UTC
**Description:**
I wanted to create a Github workflow that push feed to Azure Artifacts. I carefully followed the article [here](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/github-actions?view=azure-devops) and the tutorial [here](https://github.com/Azure/actions-workflow-samples/blob/master/PackageManagement/nuget.yml). However, I keep getting this error

`error: Unable to load the service index for source https://pkgs.dev.azure.com/<org>/<proj>/_packaging/<proj>/nuget/v3/index.json.
error:   Response status code does not indicate success: 401 (Unauthorized).`

I created a PAT for all accessible organizations, granted it full access and added it in my Github Action secrets just as the docs says but the error persists. Does anyone have idea what could be wrong here?

**Task version:**
I was using v1 but also changed to v3 but the error still occur.

**Expected behavior:**
Expecting feed to be published to Azure Artifacts

**Actual behavior:**
Build stopped and failed

**Comment by marko-zivic-93** [comment] 2023-01-13 15:46
Hello @benyusouf 
Thank you for feedback. We will investigate this issue and come back to you as soon as we have some information 🙂

**Comment by benyusouf** [comment] 2023-01-13 15:49
> Hello @benyusouf Thank you for feedback. We will investigate this issue and come back to you as soon as we have some information 🙂

Thank you @marko-zivic-93 , I'd wait for your findings

**Comment by panticmilos** [comment] 2023-01-16 15:40
hi @benyusouf, could you provide us public repo or a mock of the private repo?

**Comment by benyusouf** [comment] 2023-01-16 15:47
> hi @benyusouf, could you provide us public repo or a mock of the private repo? Or it's identical to the workflow you have posted?

Yes it's, this is what my workflow looks like

`
name: Push packages to Azure Artifacts
on:
  push:
    branches:
      - main

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/<org>/<proj>/_packaging/<proj>/nuget/v3/index.json   
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '6.x' 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and package
      - name: dotnet build and test
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
          dotnet test --configuration '${{ env.BUILD_CONFIGURATION }}'

  az-artifacts-build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
          dotnet pack -c '${{ env.BUILD_CONFIGURATION }}'

      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push --api-key az bin/Release/*.nupkg
`

I have my secret saved as AZURE_DEVOPS_TOKEN

**Comment by benyusouf** [comment] 2023-02-12 00:09
![image](https://user-images.githubusercontent.com/26325624/218286334-d5e72a12-efed-40d1-a31d-cdce0f25bdff.png)
 Hi @marko-zivic-93 @panticmilos please any update on this? I change to Github package registry, and using Github PAT with package registry scope but still getting 401 error, it's the workflow is not adding the API key or something.

**Comment by panticmilos** [comment] 2023-02-13 10:58
hi @benyusouf, thank you for your patience, I was not able to reproduce the issue, but I will give it another shot and get back to you soon :)

**Comment by benyusouf** [comment] 2023-02-13 12:00
Hi @panticmilos thank you for your response, I was able to resolve by adding `--api-key ${{ secrets.GITHUB_TOKEN }}` to `dotnet nuget push` command. My resulting command looks like:

`- name: 'dotnet publish'`
`  run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}`

This works for both Azure Artifact and Github Registry, so like I mentioned, it seems that the action is really passing the token.

**Comment by panticmilos** [comment] 2023-02-20 19:31
hi @benyusouf, in this case, I will close this issue. If you have any additional questions feel free to continue conversation here.

**Closed by panticmilos** 2023-02-20 19:31 UTC
Labels: bug

**Comment by BenjaminMichaelis** [comment] 2023-02-24 19:18
I was having this issue as well, and passing the `${{ secrets.GITHUB_TOKEN }}` did not seem to solve it. This seems like an issue since it breaks when following the documentation and since it seems like authorization isn't working properly to the artifacts feed.

**Comment by mhascak** [comment] 2023-06-30 07:22
I have tha same issue ${{ secrets.GITHUB_TOKEN }} did not helped.
