### ISSUE TITLE
Self-hosted runner install-dotnet issues with TLS

### ISSUE THREAD

**Issue by douglasrdc** [actions/setup-dotnet#189] opened 2021-04-20 12:16 UTC
**Description:**
I'm trying to run a simple action to build a .net application with a self-hosted runner. But it always returns an error saying "dotnet-install: Cannot download:". But the link for the .net zip file is correct and I'm able to download it on the server using a browser. 

After a long time trying to find a solution, I found that by changing the externals\install-dotnet.ps1 to use TLS1.2, it works fine with no errors. TLS 1.2 is enabled on the server, but even so, it doesn't work, without changing the code on the file install-dotnet.ps1.

Someone have a solution for this, or have any plan to fix this in a future version?
 
Here is where the code was changed to make it work, but every time the action run, it downloads the "fresh" scripts from the repo:

File: externals\install-dotnet.ps1
Method: function GetHTTPResponse([Uri] $Uri)
Code Added: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Task version:**
1.7.1

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x ] Windows (Windows Server 2012 R2)

**Runner type:**
- [ ] Hosted
- [x ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by maxim-lobanov** [comment] 2021-04-20 12:29
These scripts are downloaded from https://github.com/dotnet/install-scripts
I think we should report the issue to dotnet team and ask for the fix

**Comment by douglasrdc** [comment] 2021-04-20 12:51
Hi @maxim-lobanov, I just open an issue on the https://github.com/dotnet/install-scripts/issues/178 
Thanks

**Comment by maxim-lobanov** [comment] 2021-04-21 07:09
@douglasrdc , please ping us when the issue is resolved from the scripts side and we will update this action with fresh version of scripts

**Comment by douglasrdc** [comment] 2021-04-21 13:20
@maxim-lobanov I'll ping for sure. thanks

**Comment by douglasrdc** [comment] 2021-04-27 14:11
Hi @maxim-lobanov 

I got an answer from the dotnet install script team: https://github.com/dotnet/install-scripts/issues/178

Looks like, the best approach here is to add this code ( [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12) before call install-scripts.ps1 or have a way to pass a parameter with TLS version and decide with version of TLS to enable on the GetHTTPResponse method.

Please let me know if is something that can be fixed here, or else I'll assume that Windows 2012 R2 is not the best server to have this self-host action runner and need to move to a Windows 2016 server and see if it works there.

Thank you

**Comment by maxim-lobanov** [comment] 2021-04-27 17:36
Hello @douglasrdc , thank you for sharing!

Considering the rarity of the issue, I am not sure that we should integrate this command in this action.

But let's try to find another solution without updating Win2012 to Win2016:
As I understand `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` command is applied only for current PowerShell session. But I have found a few articles that describe approach to enable TLS12 for the whole machine:
- https://palmarg.wordpress.com/2014/06/09/enabling-tls-1-2-using-powershell
- https://www.msb365.blog/?p=2675
- https://community.spiceworks.com/topic/2255134-powershell-for-changing-the-tls-protocols-on-windows-server-2012

Could you please look at the article above? If it works - it is enough to apply it once and after that action will work on self-hosted machine.

**Comment by maxim-lobanov** [comment] 2021-04-27 17:39
Btw, just found how we enable TLS12 during generation of Hosted runners: https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Update-DotnetTLS.ps1
It should be even easy

**Comment by maxim-lobanov** [comment] 2021-05-24 08:20
Closing this for one since we don't have plans to integrate this functionality inside this action. Please follow guide above to configure your self-hosted runner before using action

**Closed by maxim-lobanov** 2021-05-24 08:20 UTC
Labels: bug

**Comment by cetindogu** [comment] 2021-11-14 18:23
Can you write an example 
"configure your self-hosted runner before using action"

**Comment by vsafonkin** [comment] 2021-11-15 09:26
@cetindogu, you can try to copy [this script](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Update-DotnetTLS.ps1) on your self-hosted runner and execute.
