### ISSUE TITLE
Support multiple versions in a single invocation

### ISSUE THREAD

**Issue by adamralph** [actions/setup-dotnet#146] opened 2020-11-12 19:41 UTC
I know I can do this:

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '2.1.811'
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.404'
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '5.0.100'
```

but I'd like to do this:

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-versions: ['2.1.811', '3.1.404', '5.0.100']
```

**Comment by adamralph** [comment] 2020-11-24 10:20
20 thumbs up so far. Is this worth considering?

**Comment by adamralph** [comment] 2020-12-21 11:54
![tumbleweed](https://user-images.githubusercontent.com/677704/102774435-43169280-438b-11eb-8415-cc31cbe51fb1.gif)

**Comment by coderpatros** [comment] 2020-12-31 12:30
This is a duplicate of issue #25 

It was closed, as was PR #102 without it being merged. 

I still have a solution available, details here https://github.com/actions/setup-dotnet/issues/25#issuecomment-650754771

But I would just work around it by running the action multiple times for each version. My fork is not maintained.

**Comment by adamralph** [comment] 2020-12-31 15:01
@coderpatros this is _not_ a duplicate of #25.

#25 is about allowing multiple versions to be installed, and that has indeed been fixed.

> But I would just work around it by running the action multiple times for each version. My fork is not maintained.

This is known, and it is called out in the issue description. The entire purpose of this issue is to add a feature which avoids the need for that workaround.

**Comment by adamralph** [comment] 2020-12-31 15:01
I've altered the issue title to clarify.

**Comment by coderpatros** [comment] 2020-12-31 15:15
> @coderpatros this is _not_ a duplicate of #25.
> 
> #25 is about allowing multiple versions to be installed, and that has indeed been fixed.
> 
> > But I would just work around it by running the action multiple times for each version.
> 
> This is known, and it is called out in the issue description. The entire purpose of this issue is to add a feature which avoids the need for that workaround.

True, but I think the intent was the same. All I meant was don’t hold your breath.

**Comment by adamralph** [comment] 2020-12-31 16:06
The intent is different.

#25 was about allowing multiple versions. That issue was addressed and multiple versions are now allowed, but it requires multiple invocations.

This issue is about allowing multiple versions in a single invocation.

**Comment by adamralph** [comment] 2021-05-05 14:47
It made me a little sad to see 1.8.0 released without this feature.

It was raised 7 months agoand has _by far_ the most 👍 of any feature request.

**Comment by adamralph** [comment] 2021-06-26 20:00
Is there anything that I (or anyone else) can do to help get this prioritised?

**Comment by vsafonkin** [comment] 2021-06-28 11:00
Hi @adamralph, unfortunately this improvement is not considered a priority at the moment. Probably it will be implemented in v2 version of the action. Sorry that it takes so much time.

**Comment by adamralph** [comment] 2021-06-28 11:28
@vsafonkin thanks for the update.

FWIW, this is the first time (to my knowledge) that a maintainer has commented on this issue. Given the enthusiasm shown for it (currently 36 upvotes) it would be nice to have received some response a little earlier, even if it is just "not now, but later". It's good to know that you have this in your sights. 👍

**Comment by vsafonkin** [comment] 2021-06-28 11:36
@adamralph, thank you for your patience.

**Closed** 2021-11-23 10:03 UTC
Labels: feature request
