### ISSUE TITLE
Task.Delay test fails consistently on runner but pass locally

### ISSUE THREAD

**Issue by rmandvikar** [actions/setup-dotnet#400] opened 2022-11-25 22:39 UTC
### Description

I'm hitting a bug that I can tldr to below test. A `Task.Delay(n)` for `n` ms, doesn't delay for `n` ms when compared with a `Stopwatch` on net6.0, and net7.0 on the runner. 

```cs
//     <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
		[Test]
		[TestCase(25)]
		[TestCase(5)]
		[TestCase(0)]
		[TestCase(50)]
		[TestCase(100)]
		public async Task __(int delayInMilliseconds)
		{
			const int iterations = 10;
			for (int i = 0; i < iterations; i++)
			{
				var stopwatch = Stopwatch.StartNew();
				await Task.Delay(delayInMilliseconds).ConfigureAwait(false);
				stopwatch.Stop();

				Assert.GreaterOrEqual(stopwatch.ElapsedMilliseconds, delayInMilliseconds);
			}
		}
```

The result I'm getting from runner is:
```
// net6.0
  Passed __(25) [278 ms]
  Passed __(5) [79 ms]
  Passed __(0) [< 1 ms]
  Passed __(50) [519 ms]
  Failed __(100) [607 ms]
  Error Message:
     Expected: greater than or equal to 100
  But was:  98
```

The behavior is similar on net7.0 too: 
```
// net7.0
  Passed __(25) [282 ms]
  Passed __(5) [75 ms]
  Passed __(0) [< 1 ms]
  Passed __(50) [527 ms]
  Failed __(100) [121 ms]
  Error Message:
     Expected: greater than or equal to 100
  But was:  96
```

I have multiple runs below, and the test consistently fails on the runners. It always passes locally.

runs:
https://github.com/rmandvikar/delegating-handlers/actions/runs/3551050455
https://github.com/rmandvikar/delegating-handlers/actions/runs/3551034276
https://github.com/rmandvikar/delegating-handlers/actions/runs/3551020420

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.299.1'
Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20221119.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221119.2/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221119.2
Runner Image Provisioner
  2.0.91.1
```

### Is it regression?

No

### Expected behavior

The test should pass the delay must be 100+ ms. 

### Actual behavior

The test fails as the delay is 98 ms instead of 100+ ms. (net6.0)
The test fails as the delay is 96 ms instead of 100+ ms. (net7.0)

### Repro steps

1. Run mentioned test locally (passes)
2. Run mentioned test on the runner (fails)

**Comment by IvanZosimov** [comment] 2023-07-21 09:22
Hi, @rmandvikar 👋 Sorry for the delay. Unfortunately, it seems that this issue isn't related to the `setup-dotnet` itself. It's caused by the logic behind `Task.Delay()` and `Stopwatch`. These tools are pretty inaccurate in the range of times near to the system clock resolution and it seems like a very common issue for the NET developers. I did replicated the issue on my local machine, so it's not related to the runner's infrastructure too.

I'm going to close the issue now, If you have any additional questions feel free to ping me.

**Closed by IvanZosimov** 2023-07-21 09:22 UTC
Labels: bug
