### ISSUE TITLE
[Info] dotnet ^7.0.2* introduced an MSBuild preview version with breaking changes.

### ISSUE THREAD

**Issue by snwflake** [actions/setup-dotnet#383] opened 2023-02-18 02:02 UTC
**Description:**
For reference: https://github.com/dotnet/sdk/issues/30624

The MSBuild preview version provided with 7.0.200 introduced breaking changes and generally [ill-formed behavior](https://github.com/dotnet/razor/issues/8281).

Pinning the version to anything below 7.0.200, ie. 7.0.103 does not resolve that issue, as the same MSBuild preview is still being used.

My workaround so far has been to add another step after the dotnet-setup which just removes 7.0.2* sdk versions. Only then started my build to produce working output with proper viewcomponents.

**Task version:**
[926f442](https://github.com/actions/setup-dotnet/commit/926f4420227aaf87acf2840f360e4f2475f13b3b)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yml
- name: Setup .net
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.0.103
```

```
dotnet publish app -c Release -o ~/deploy
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
```

**Notes:**
While this is a bug introduced by the SDK, I still wanted to raise this issue here, to spare others from wasting 3 hours debugging it.
The workaround for me is currently the following until the [announced hotfix 7.0.201](https://github.com/dotnet/sdk/issues/30624#issuecomment-1435408741) goes live:

```yml
- name: Setup .net
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.0.103
- name: Remove faulty SDK version
  run: sudo rm -rf /usr/share/dotnet/sdk/7.0.2*
```

**Comment by panticmilos** [comment] 2023-02-20 09:44
hi @snwflake, thank you for the report, we will take a look at it :)

**Comment by snwflake** [comment] 2023-02-21 16:32
@danielriddellsh sorry, should have copy&pasted.

**Comment by Shane32** [comment] 2023-02-25 16:15
7.0.201 has been released but it’s not picked up by setup-dotnet. Anyone know what’s up?

**Comment by edumserrano** [comment] 2023-02-26 20:15
I just wanted to leave here that one of the [workarounds described here](https://github.com/dotnet/sdk/issues/30624#issuecomment-1435454747) worked for me.

What I did was make use of a `global.json` file to pin the version of dotnet to `7.0.103`. I also had to make sure that my `dotnet` CLI commands were picking up the `global.json` file. See the note below.

This fixed the issue for me without having to remove the default installation of dotnet SDK `7.0.200` from the GitHub runner. I just need to make sure that the `actions/setup-dotnet@v3` installs a previous working version such as `7.0.103`. You can review here an example of the PRs I've made on my repos to fix this issue: edumserrano/github-issue-forms-parser#28.

>**Note**
>
> As per the [global.json overview docs](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json):
> "The .NET SDK looks for a global.json file in the current working directory (which isn't necessarily the same as the project directory) or one of its parent directories."
>
> This means that you need to be careful regarding what the working directory where you run the `dotnet` CLI commands is to make sure the `global.json` file is respected.

**Comment by stunney** [comment] 2023-02-28 22:04
6.0.* also has breaking issues with `dotnet pack --output` as well.  This is due to a preview version of MSBuild being tacked onto the `setup-dotnet` GHA that I don't think was intended.

https://github.com/dotnet/core/issues/8245

**Comment by AZ-X** [comment] 2023-03-21 06:58
It's a terrible release, isn't it?
I gotter face strange NETSDK1168 unexpectedly...

**Comment by tgrnwd** [comment] 2023-04-12 19:46
My experience seems to be that running any `dotnet` command in conjunction with `v3` of this action is using the latest SDK, even though I specify `6.0.x` in the `setup-dotnet` action.

Falling back to `v2` of this action produces the expected behavior.

**Comment by IvanZosimov** [comment] 2023-04-13 07:28
Hi, @tgrnwd 👋 The `v3` release contains some breaking changes and it's behaviour is different from `v2` version. Please, refer to this part of documentation to get additional information https://github.com/actions/setup-dotnet#usage.

**Comment by tgrnwd** [comment] 2023-04-13 12:42
@IvanZosimov Ah, thank you. I'm certain I read this, but didn't fully understand at that time.

**Comment by IvanZosimov** [comment] 2023-07-07 12:17
I'm closing this issue as the NET SDK 7.0.201 was released and it seems to solve the problem.

**Closed by IvanZosimov** 2023-07-07 12:17 UTC
Labels: external
