### ISSUE TITLE
[Help] error NU1301: Unable to load the service index for source

### ISSUE THREAD

**Issue by baltermia** [actions/setup-dotnet#425] opened 2023-05-17 06:58 UTC
**Description:**
The Github Action fails when restoring nuget packages. The error message is as follows:
> error NU1301: Unable to load the service index for source https://dotnet.myget.org/F/blazor-dev/api/v3/index.json.

**Task version:**
V3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
Here's my workflow file: [dotnet.yml](https://github.com/baltermia/blazor-camera-streamer/blob/main/.github/workflows/dotnet.yml)

**Expected behaviour:**
NuGet packages should be restored successfully.

**Actual behaviour:**
```
Build FAILED.

       "D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer.sln" (Restore target) (1) ->
       (Restore target) -> 
         D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer\BlazorCameraStreamer.csproj : error NU1301: Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. [D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer.sln]
         D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer\BlazorCameraStreamer.csproj : error NU1301: Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. [D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer.sln]
         D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer\BlazorCameraStreamer.csproj : error NU1301: Unable to load the service index for source https://dotnet.myget.org/F/blazor-dev/api/v3/index.json. [D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer.sln]
         D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer\BlazorCameraStreamer.csproj : error NU1301: Unable to load the service index for source https://dotnet.myget.org/F/blazor-dev/api/v3/index.json. [D:\a\blazor-camera-streamer\blazor-camera-streamer\BlazorCameraStreamer.sln]

    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:32.60
Error: Process completed with exit code 1.
```

Here's one of my latest runs: https://github.com/baltermia/blazor-camera-streamer/actions/runs/5000120116/jobs/8957149593

**Comment by marko-zivic-93** [comment] 2023-05-17 14:32
Hello @baltermia ,

Thank you for the heads up. We have already started to investigate this issue. We will come back to you as soon as we have some updates. 🙂

**Comment by nikolai-laevskii** [comment] 2023-05-17 16:17
Hello @baltermia,

Thank you for reporting the issue! Unfortunately we can not do much about this right now. It appears the problem is related to myget.org service availability. As for now you can try re-running jobs. Availability of myget.org is inconsistent but it seems to respond most of the time.

**Comment by IvanZosimov** [comment] 2023-07-03 08:50
Hi, @ciuliene and @baltermia 👋 Do you still face the issue? Do you face it running build command locally ?

**Comment by baltermia** [comment] 2023-07-04 08:43
Hi @IvanZosimov, the issue unfortunately still persists for me. 

Could you tell me what you mean by "running build command locally"?

Thanks in advance.

**Comment by baltermia** [comment] 2023-07-04 09:07
@IvanZosimov sorry for my confusion. No, the error does not appear on my local machine when building the project. It seems to be an issue within the github action. It seems a bit weird to me since @nikolai-laevskii could not reproduce the issue in his fork when also running actions.

I run an almost identical action in other repositories and these work fine. To me it seems to be a problem in my specific repository.

**Comment by IvanZosimov** [comment] 2023-07-04 09:15
@baltermia, no problem at all! I'll try to reproduce the issue one more time and get back to you with results.

**Comment by IvanZosimov** [comment] 2023-07-04 09:47
@baltermia, I just tried to reproduce the problem using the repository you mentioned in the issue. It turns out that sometimes restoring dependencies fails, sometimes it doesn't (check these 4 attempts out https://github.com/IvanZosimov/blazor-camera-streamer/actions/runs/5453001942). I tried to restore dependencies on my local machine (not using setup-dotnet action at all) and it also failed occasionally. So in my opinion this problem isn't related to the action itself, but it's related to the source of the packages you use.

Now I'm going to close this issue, If you have any additional questions, feel free to ping me!

**Closed by IvanZosimov** 2023-07-04 09:47 UTC
Labels: external
