### ISSUE TITLE
Installs latest SDK version before it is available/is released.

### ISSUE THREAD

**Issue by VMelnalksnis** [actions/setup-dotnet#381] opened 2023-02-14 17:00 UTC
**Description:**
The latest version in both https://dotnet.microsoft.com/en-us/download/dotnet/7.0 and https://github.com/dotnet/core/releases is 7.0.2 (`dotnet --version 7.0.102`), however `setup-dotnet` installed `7.0.200` with the following `global.json` file:
```json
{
	"sdk": {
		"version": "7.0.102",
		"rollForward": "latestFeature",
		"allowPrerelease": false
	}
}
```
I understand that this follows the `rollForward` settings, however I don't expect it to install unreleased versions that break the build.

**Task version:**
3.0.3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Here's a link to the run that installed the unreleased version - https://github.com/VMelnalksnis/Gnomeshade/actions/runs/4175978230/jobs/7231771550

**Expected behavior:**
`setup-dotnet` installs versions that have been released/have release notes.

**Actual behavior:**
`setup-dotnet` installs unpublished versions with breaking changes and without release notes.

**Comment by panticmilos** [comment] 2023-02-16 19:10
hi @VMelnalksnis, thank you for the report, we will take a look at it :)

**Comment by dmitry-shibanov** [comment] 2023-02-17 15:15
Hello @VMelnalksnis. Thank you for your report. I think it is an expected behaviour because when you set up [rollForward to latestFeature](https://github.com/actions/setup-dotnet/issues/223) the action will try [to install the latest patch version](https://github.com/actions/setup-dotnet/blob/main/src/setup-dotnet.ts#L108-L115). The action rely on [releases.json](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/7.0/releases.json) that is why if the version is available there it will be installed. 

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-02-17 15:15 UTC
Labels: bug

**Comment by VMelnalksnis** [comment] 2023-02-17 15:21
That's weird, because at the time I checked the index - https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json - and it was still 7.0.2/7.0.102, but alright. Then I guess it's just an issue in the release of .NET.
