### ISSUE TITLE
Proxy Setup fail with self-hosted runner

### ISSUE THREAD

**Issue by yannou38** [actions/setup-dotnet#558] opened 2024-10-23 14:16 UTC
**Description:**
When trying to use the action, i get an error when the action try to set the proxy object

```
New-Object : La valeur fournie n'est pas valide ou la propriété est en lecture seule. Modifiez la valeur, puis 
réessayez.
Au caractère C:\ghr\IOTSEC-gh-actions\1\_work\_actions\actions\setup-dotnet\c7e7147fd3e41056e75a761416c06f5fa781b5fb\ex
ternals\install-dotnet.ps1:366 : 45
  ... ttpClientHandler.Proxy =  New-Object System.Net.WebProxy -Property @{
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CategoryInfo          : InvalidData : (:) [New-Object], Exception
      FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand
```

**Task version:**
commit id c7e7147fd3e41056e75a761416c06f5fa781b5fb

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Repro steps:**  
- Set a proxy in system env variable on your selfhosted runner
- run action
```
- name: test setup dotnet
        id: testdotnet
        uses: actions/setup-dotnet@c7e7147fd3e41056e75a761416c06f5fa781b5fb
        with:
          dotnet-version: '7'
```
**Expected behavior:**
Proxy should be set and dotnet should get downloaded

**Actual behavior:**
Error pasted above

**Comment by priyagupta108** [comment] 2024-10-24 03:39
Hi @yannou38 👋,
Thank you for your report. We'll investigate the issue and get back to you with the details!

**Comment by gowridurgad** [comment] 2024-11-05 05:17
Hi @yannou38, We are unable to reproduce the error you are experiencing. We've successfully installed the dotnet without encountering any errors. Here are a few troubleshooting steps to help resolve the issue.
Proxy Settings: Verify that your proxy settings are correctly configured and that the values provided are valid.
Try Different Proxy: If possible, test with a different proxy server to rule out issues specific to the current proxy.
Check Self-Hosted Runner Configuration: Ensure that the self-hosted runner is configured correctly and has the necessary permissions to set the proxy and run the script.
Run Script Locally: Try running the install-dotnet.ps1 script locally to see if the issue persists outside of the GitHub Actions environment.
If the problem continues, please provide more details about your environment , setup and attach link to the build or public repository . so we can assist further.

**Comment by gowridurgad** [comment] 2024-11-18 11:53
Hi @yannou38, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment] 2024-11-25 11:51
Hi @yannou38, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by yannou38** [comment] 2024-11-25 12:08
> * **Proxy Settings:** Verify that your proxy settings are correctly configured and that the values provided are valid.
The settings are correct, the other actions requiring those values work nicely
> * **Try Different Proxy:** If possible, test with a different proxy server to rule out issues specific to the current proxy.
Not possible as it's my company proxy.
> * **Check Self-Hosted Runner Configuration:** Ensure that the self-hosted runner is configured correctly and has the necessary permissions to set the proxy and run the script.
The runner should have the needed rights, but what do you call "set the proxy" ? it's already set beforehand. 
> * **Run Script Locally:** Try running the install-dotnet.ps1 script locally to see if the issue persists outside of the GitHub Actions environment.
Haven't tried that yet, as other matters took priority, but i'll try to do so in a reasonable timeframe. I don't expect it to fare better if ran manually however.
> If the problem continues, please provide more details about your environment, setup and attach link to the build or public repository. So we can assist further.
I can not share details about the build as it's private, company owned. The self-hosted runner is on a windows machine and not containerized if that helps.

**Comment by gowridurgad** [comment] 2024-11-27 06:40
Hi @yannou38, Since the action works as expected in a containerized instance, it seems the issue may be specific to your system . I understand you can't share the private build, but if you’re able to reproduce the issue in a public repository, please feel free to share it. I’m going to close this issue for now, but we’re here to assist you should you need any additional support. Feel free to reach out or reopen the issue if needed.

**Closed by gowridurgad** 2024-11-27 06:40 UTC
Labels: bug
